//! @generated by lumen-agent session.exportTest (M2-exit). Do not edit.
#[test]
fn agent_regression() {
    lumen_test::block_on(async {
        let app = lumen_test::TestApp::new(settings::main_app());
        app.locator("tab:nth(3)").click().await.unwrap();
        lumen_test::expect(app.locator("#about"))
            .to_have_text("Lumen Settings 1.0")
            .await
            .unwrap();
        app.locator("tab:nth(2)").click().await.unwrap();
        app.locator("#dark_mode").click().await.unwrap();
        lumen_test::expect(app.locator("#dark_mode"))
            .to_have_state("checked")
            .await
            .unwrap();
    });
}
