//! M2-exit acceptance: an agent connected only to lumen-agent (over a real
//! WebSocket) explores the settings app and exports a regression suite. The
//! exported suite is committed alongside as `agent_regression.rs` and runs
//! green via `cargo test --workspace` (3 OSes in CI); this test proves the
//! agent's live export matches that committed file.

use lumen_agent::{serve_one_session, Session};
use lumen_core::geometry::Size;
use serde_json::{json, Value};
use std::path::PathBuf;
use tungstenite::Message;

fn call<S: std::io::Read + std::io::Write>(
    ws: &mut tungstenite::WebSocket<S>,
    method: &str,
    params: Value,
) -> Value {
    let req = json!({ "jsonrpc": "2.0", "id": 1, "method": method, "params": params });
    ws.send(Message::Text(req.to_string())).unwrap();
    loop {
        if let Message::Text(t) = ws.read().unwrap() {
            return serde_json::from_str(&t).unwrap();
        }
    }
}

fn committed_suite() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/agent_regression.rs")
}

#[test]
fn agent_explores_and_exports_regression_suite() {
    let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
    let port = listener.local_addr().unwrap().port();

    let server = std::thread::spawn(move || {
        let mut app = settings::main_app().run_headless(Size::new(480.0, 360.0));
        app.pump();
        let mut session = Session::new();
        serve_one_session(&listener, &mut app, &mut session).unwrap();
    });

    let (mut ws, _) = tungstenite::connect(format!("ws://127.0.0.1:{port}/agent")).unwrap();

    // Explore: start on General, jump to About, assert its text…
    assert!(call(&mut ws, "ui.getTree", json!({}))["result"]
        .to_string()
        .contains("Notifications"));
    assert_eq!(
        call(&mut ws, "input.click", json!({ "selector": "tab:nth(3)" }))["result"]["ok"],
        json!(true)
    );
    assert_eq!(
        call(
            &mut ws,
            "session.assertText",
            json!({ "selector": "#about", "equals": "Lumen Settings 1.0" })
        )["result"]["ok"],
        json!(true)
    );

    // …then Appearance, toggle dark mode, assert it became checked.
    call(&mut ws, "input.click", json!({ "selector": "tab:nth(2)" }));
    call(&mut ws, "input.click", json!({ "selector": "#dark_mode" }));
    assert_eq!(
        call(
            &mut ws,
            "session.assertState",
            json!({ "selector": "#dark_mode", "state": "checked" })
        )["result"]["ok"],
        json!(true)
    );

    // Export the recorded session as a standalone lumen-test.
    let exported = call(
        &mut ws,
        "session.exportTest",
        json!({
            "fnName": "agent_regression",
            "appExpr": "settings::main_app()",
            "header": "//! @generated by lumen-agent session.exportTest (M2-exit). Do not edit.",
        }),
    );
    let source = exported["result"]["source"].as_str().unwrap();

    // The export is a valid lumen-test replaying the exploration.
    assert!(source.contains("fn agent_regression()"));
    assert!(source.contains(r##"app.locator("tab:nth(3)").click()"##));
    assert!(source.contains(r##"to_have_text("Lumen Settings 1.0")"##));
    assert!(source.contains(r##"app.locator("#dark_mode").click()"##));
    assert!(source.contains(r##"to_have_state("checked")"##));

    // It matches the committed regression suite that CI runs on 3 OSes. Compare
    // token-wise (whitespace-insensitive) so rustfmt may reflow the committed
    // file without breaking this check — rustfmt only changes whitespace.
    let committed =
        std::fs::read_to_string(committed_suite()).expect("committed regression suite must exist");
    let normalize = |s: &str| s.chars().filter(|c| !c.is_whitespace()).collect::<String>();
    assert_eq!(
        normalize(source),
        normalize(&committed),
        "agent export drifted from committed suite; regenerate it"
    );

    drop(ws);
    server.join().unwrap();
}
