//! color_palette — a row of swatches generated by rotating hue in Oklab,
//! rendered on a Canvas and centred in a soft-shadowed panel.
use kurbo::Rect;
use lumen_core::Color;
use lumen_widgets::{theme, widgets, App, BuildCx, Element};

/// Build the color-palette app.
pub fn main_app() -> App {
    App::new(build)
}

fn build(cx: &mut BuildCx) -> Element {
    let n = cx.signal("n", || 6usize);
    let count = n.get(cx.runtime());
    let strip = widgets::canvas(300.0, 64.0, move |f, size| {
        let gap = 8.0;
        let w = (size.width - gap * (count as f64 - 1.0)) / count as f64;
        for i in 0..count {
            let hue = i as f32 / count as f32 * std::f32::consts::TAU;
            let c = Color::from_oklch(0.72, 0.15, hue.to_degrees());
            let x = i as f64 * (w + gap);
            let rect = Rect::new(x, 0.0, x + w, size.height);
            f.fill_rounded_rect(rect, 10.0, c);
        }
    })
    .id("palette");
    theme::center_screen(theme::panel_centered(widgets::column(vec![
        strip,
        theme::caption(format!("{count} colors")).id("count"),
        theme::button_row(vec![
            theme::ghost_button("Fewer", move |rt| n.update(rt, |x| *x = (*x - 1).max(2)))
                .id("fewer"),
            theme::accent_button("More", move |rt| n.update(rt, |x| *x = (*x + 1).min(12)))
                .id("more"),
        ]),
    ])))
}
