//! color_palette — a row of swatches generated by rotating hue in Oklab,
//! rendered on a Canvas.
use kurbo::Rect;
use lumen_core::Color;
use lumen_render::display_list::Brush;
use lumen_widgets::{theme, widgets, App, BuildCx, Element};

/// Build the color-palette app.
pub fn main_app() -> App {
    App::new(build)
}

fn build(cx: &mut BuildCx) -> Element {
    theme::screen("Color palette", body(cx))
}

fn body(cx: &mut BuildCx) -> Element {
    let n = cx.signal("n", || 6usize);
    let count = n.get(cx.runtime());
    let strip = widgets::canvas(240.0, 48.0, move |f, size| {
        let w = size.width / count as f64;
        for i in 0..count {
            let hue = i as f32 / count as f32 * std::f32::consts::TAU;
            let c = Color::from_oklch(0.7, 0.15, hue.to_degrees());
            f.fill_rect(
                Rect::new(i as f64 * w, 0.0, (i as f64 + 1.0) * w, size.height),
                Brush::Solid(c),
            );
        }
    })
    .id("palette");
    widgets::column(vec![
        strip,
        widgets::row(vec![
            widgets::button("fewer", move |rt| n.update(rt, |x| *x = (*x - 1).max(2))).id("fewer"),
            widgets::text(format!("{count} colors")).id("count"),
            widgets::button("more", move |rt| n.update(rt, |x| *x = (*x + 1).min(12))).id("more"),
        ]),
    ])
}
