//! The v1 `.lss` property name set (04 §3). Used for E0102 did-you-mean.

/// All recognized property names.
pub const KNOWN_PROPERTIES: &[&str] = &[
    // layout
    "display",
    "flex-direction",
    "flex-wrap",
    "flex-grow",
    "flex-shrink",
    "flex-basis",
    "justify-content",
    "align-items",
    "align-self",
    "align-content",
    "gap",
    "row-gap",
    "column-gap",
    "grid-template-columns",
    "grid-template-rows",
    "grid-column",
    "grid-row",
    "width",
    "height",
    "min-width",
    "min-height",
    "max-width",
    "max-height",
    "aspect-ratio",
    "padding",
    "padding-top",
    "padding-right",
    "padding-bottom",
    "padding-left",
    "margin",
    "margin-top",
    "margin-right",
    "margin-bottom",
    "margin-left",
    "position",
    "inset",
    "inset-top",
    "inset-right",
    "inset-bottom",
    "inset-left",
    "overflow",
    // visual
    "background",
    "border",
    "border-top",
    "border-right",
    "border-bottom",
    "border-left",
    "border-radius",
    "shadow",
    "opacity",
    "blend-mode",
    "filter",
    "backdrop-filter",
    "clip",
    "transform",
    "transform-origin",
    "z-index",
    "visibility",
    "cursor",
    // typography
    "font-family",
    "font-size",
    "font-weight",
    "font-style",
    "font-features",
    "font-variation",
    "line-height",
    "letter-spacing",
    "color",
    "text-align",
    "text-overflow",
    "text-wrap",
    "text-decoration",
    "selection-color",
    // motion
    "transition",
    "animation",
    "animation-force",
];
